/* Query 4 - query used for fourth insight */

-- How many customers have maintained or increased their spendings on movie rentals each month? ---
WITH
	MONTLY_PAYMENTS AS (
		SELECT
			C.CUSTOMER_ID,
			DATE_TRUNC('month', PAYMENT_DATE) AS PAYMENT_DATE,
			SUM(P.AMOUNT) SPENDINGS
		FROM
			CUSTOMER C
			JOIN PAYMENT P ON C.CUSTOMER_ID = P.CUSTOMER_ID
		GROUP BY 1,	2
		ORDER BY 1,	2
	),
	DECREASE_INCREASE AS (
		SELECT
			CUSTOMER_ID,
			PAYMENT_DATE,
			CASE
				WHEN SPENDINGS - LAG(SPENDINGS) OVER (PARTITION BY	CUSTOMER_ID	ORDER BY PAYMENT_DATE) >= 0 THEN 1 
				ELSE 0
			END INCREASE_SAME,
			CASE
				WHEN LAG(SPENDINGS) OVER (PARTITION BY CUSTOMER_ID	ORDER BY PAYMENT_DATE) IS NULL THEN 0
				ELSE 1
			END NOT_NULL
		FROM
			MONTLY_PAYMENTS
	)
SELECT
	PAYMENT_DATE,
	COUNT(*) AS CUSTOMERS,
	SUM(INCREASE_SAME)AS INCREASE_SAME,
	SUM(
		CASE
			WHEN INCREASE_SAME = 0 THEN 1
			ELSE 0
		END
	) AS DECREASE
FROM
	DECREASE_INCREASE
WHERE
	NOT_NULL = 1
GROUP BY
	1
ORDER BY
	1
