/* Query 2 - query used for second insight */

-- How has the revenue in family-friendly and other categories changed on a monthly basis? --

WITH
	REVENUE_CAT AS (
		SELECT
			CASE
				WHEN C.NAME IN ('Animation', 'Children', 'Classics', 'Comedy', 'Family') THEN 'Family-friendly'
				ELSE 'Other'
			END CAT_FAMILY,
			DATE_TRUNC('month', P.PAYMENT_DATE) PAYMENT_MONTH,
			SUM(P.AMOUNT) REVENUE
		FROM
			RENTAL R
			JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
			JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
			JOIN FILM F ON I.FILM_ID = F.FILM_ID
			JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
			JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
		GROUP BY 1, 2
		ORDER BY 1, 2
	)

SELECT 
	CAT_FAMILY,
	PAYMENT_MONTH,
	REVENUE,
	REVENUE - LAG(REVENUE) OVER (PARTITION BY CAT_FAMILY ORDER BY PAYMENT_MONTH) REVENUE_DIFFERENCE
FROM REVENUE_CAT
ORDER BY
	CAT_FAMILY,
	PAYMENT_MONTH