/* Query 1 - query used for first insight */

-- How do the top 10 grossing genres compare in revenue? --

SELECT C.NAME CATEGORY, SUM(P.AMOUNT) REVENUE
FROM
	FILM F
	JOIN FILM_CATEGORY FC ON F.FILM_ID = FC.FILM_ID
	JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
	JOIN INVENTORY I ON F.FILM_ID = I.FILM_ID
	JOIN RENTAL R ON I.INVENTORY_ID = R.INVENTORY_ID
	JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10